### ISSUE TITLE
500 Internal Server Error: ActiveRecord Connection Timeout (block in wait pool) since adding

### ISSUE THREAD

**Issue by omgaz** [spree-contrib/spree_static_content#167]
I've recently added `spree_static_content` gem for use with spree. However I'm noticing 500 errors happening every few hours which are requiring a server restart. AWS shows me my number of database connections went from a constant and static 2 over the last few weeks, to jumping to my pool max of 5 immediently after adding and commiting spree_static_content.

I'm guessing there's open conenctions that aren't being closed.

Front-end is failing with.

```
500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.
```

With the following partial stack in the logs.

```
FATAL – : 
ActiveRecord::ConnectionTimeoutError (could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)):
activerecord (4.1.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:190:in `block in wait_poll'
activerecord (4.1.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:181:in `loop'
activerecord (4.1.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:181:in `wait_poll'
activerecord (4.1.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:136:in `block in poll'
```

I'm not sure if it's related but it also looks suspicious that I get the following message when I start my server.

```
Instance method "open" is already defined in Object, use generic helper instead or set StateMachine::Machine.ignore_method_conflicts = true.
```

I've been using the Spree 2.4.0 Beta, with no problems for the last few weeks running ruby '2.1.2' and rails '4.1.4'.

The only change in my commit prior to the problems was adding in spree_static_content, some CSS for the header and footer navigation, and adding a reference in my footer template.

```
ul.nav
    = render :partial => "spree/static_content/static_content_list", :collection => Spree::Page.visible.footer_links, :as => :page
```

Can someone please help resolve this problem.

**Comment by toymachiner62** [comment]
What did you add Passenger and Nginx to? I'm having this same issue with a non-spree project and i'm stumped.
