### ISSUE TITLE
Unhook repo fork.

### ISSUE THREAD

**Issue by futhr** [spree-contrib/spree_static_content#174]
Hi, https://github.com/spree-contrib/spree_static_content should not be a fork when its the one being maintained. All credits about origin are still intact in the license etc.

**Comment by peterberkenbosch** [comment]
Totally agree @futhr, I will update the forked repo and transfer the ownership.

**Comment by futhr** [comment]
Same for these that have activity:

- spree_multi_domain @JDutil
- spree_volume_pricing @JDutil
- spree_editor @romul 
- spree-product-assembly @romul 
- spree_recently_viewed
- spree_comments @romul (but uses secondary fork)

**Comment by JDutil** [comment]
Looks like they finally removed me from the railsdog organization so I can't transfer those, but @BDQ could.

**Comment by JDutil** [comment]
@futhr BDQ no longer has access to transfer Rails Dog forks either.  Perhaps @dhonig will transfer the Rails Dog ones.  I'm also not sure how to contact @romul aside from github mention so maybe he will see this and transfer them.  Otherwise they'll have to remain forks and/or we delete and recreate the repos as canonical.

**Comment by dhonig** [comment]
Happy to help. Let me know what the best course of action isOn Thu, Jan 29, 2015 at 12:27 PM,  Jeff Dutil <notifications@github.com> wrote:            @futhr BDQ no longer has access to transfer Rails Dog forks either.  Perhaps @dhonig will transfer the Rails Dog ones.  I'm also not sure how to contact @romul aside from github mention so maybe he will see this and transfer them.  Otherwise they'll have to remain forks and/or we delete and recreate the repos as canonical.

**Comment by futhr** [comment]
@dhonig, they ideal is to transfer ownership to spree-contrib, then no forks nor stars are lost, very easy done in Github settings. Thanks.

**Comment by dhonig** [comment]
I'm happy to transfer any extensions out of RailsDog that we are not
actively developing to spree-contrib  doesn't look like we are the origin
author of spree-static-content
https://github.com/pero-ict-solutions/spree-static-content

**Comment by futhr** [comment]
Its `spree_multi_domain` and `spree_volume_pricing` that's under RailsDog's command. This just ended up as a general thread for all repos that need to be transferred.

**Comment by futhr** [comment]
@divineforest are you interested to transfer ownership for `spree_editor` to spree-contrib?

**Comment by dhonig** [comment]
I don't think I should need admin rights to spree-contrib to  transfer a
repo, do I?

https://www.dropbox.com/s/wynb95yszlm05e4/Screenshot%202015-01-29%2014.47.37.png?dl=0

**Comment by futhr** [comment]
No you don't need that. It should look like this as example:

Step 1:
![screen shot 2015-01-29 at 20 57 50](https://cloud.githubusercontent.com/assets/66969/5965086/9e63a9e0-a7f9-11e4-84c8-e0448ea62d17.png)

Step 2:

![screen shot 2015-01-29 at 20 57 18](https://cloud.githubusercontent.com/assets/66969/5965092/a83c8310-a7f9-11e4-90a4-4c551f7a9d60.png)

**Comment by dhonig** [comment]
Something is funky with this
I can connect *@JDutil and we can figure this out.

**Comment by JDutil** [comment]
@futhr I think you're able to transfer as you've been added to spree-contrib organization.  I've sent @dhonig an invite and hopefully that resolves the issue.

**Comment by futhr** [comment]
Yes, that's correct, I tested to transfer my repo to thoughtbot but got same access error.

**Comment by dhonig** [comment]
drat. @JDutil  accepted invite and still saying I need admin rights.

**Comment by divineforest** [comment]
@futhr yes, sure :)

**Comment by divineforest** [comment]
@futhr I also need admin rights on `spree-contrib`

**Comment by romul** [comment]
Hi all. 
> I'm also not sure how to contact @romul aside from github

You can get my email from any repository: `git log | grep "Roman Smirnov"` ;-)

@futhr That's a little bit surprising but I also need admin rights on spree-contrib 
And I'm not sure about spree_recently_viewed. Atm spree-contrib contains a fork of fork of my repo.

**Comment by futhr** [comment]
Yes i hope Github clever enough to swap transfers correctly, no clue why it was forked from a fork without additions.

@JDutil can you add @dhonig @romul and @divineforest as contributors?

**Comment by JDutil** [comment]
We can't transfer already existing repos @peterberkenbosch tried with this repo already.  We'd have to delete the existing repositories that are up to date and have the out of date forks transferred.  While I'm sure we could just update those guys forks, give them access, and then have them transfer I'd rather not risk them getting messed up or inconvenience people trying to use the projects during the transition period.

**Comment by futhr** [comment]
Closing this then, and writing an angry message to Github staff ;)
