### ISSUE TITLE
Looks like install generator doesn't work for Spree 3.0

### ISSUE THREAD

**Issue by romul** [spree-contrib/spree_static_content#178]
`bundle exec rails g spree_static_content:install` freezes and doing nothing.

**Comment by romul** [comment]
It was related to `spring`. 
When I removed it from Gemfile, problem was gone.

**Comment by futhr** [comment]
You can just lock spring to v1.2.0 to avoid the issue, v1.3.0 seems problematic.

**Comment by futhr** [comment]
@romul spring v1.3.1 was released 16 hours ago did you try that version? they might have fixed the binstub issue.

**Comment by romul** [comment]
@futhr yeah, I've catched [this issue](https://github.com/rails/spring/issues/265) on spring 1.3.1 )
