### ISSUE TITLE
How to remove sidebar from static pages?

### ISSUE THREAD

**Issue by renshah** [spree-contrib/spree_static_content#183]
Hi,

I am able to see sidebar in each static page. How can i remove it from only static page?

**Comment by marrax** [comment]
Did you get answer to this ? , I'm in the same situation

**Comment by renshah** [comment]
Hi Marrax,

I didn't get reply for it. I override spree_application file and removed sidebar code from it. 
I have commented this line in spree_application layout file.

	        <%#= render :partial => 'spree/shared/sidebar' if content_for? :sidebar %>

Regards,

**Comment by mynameisjeffe** [comment]
Here is the code to remove the sidebar:

# app/overrides/my_override.rb
Deface::Override.new(:virtual_path => "spree/shared/_sidebar",
                     :name => "remove_sidebar",
                     :remove => "aside#sidebar")
