### ISSUE TITLE
branch 3-0-stable

### ISSUE THREAD

**Issue by ristovskiv** [spree-contrib/spree_static_content#184]
There is a minor bug in "overrides/pages_in_header.rb". Instead of
>Deface::Override.new(:virtual_path => "spree/shared/_main_nav_bar",
                     :name => "pages_in_header",
                     :insert_bottom => "#main-nav-bar",
                     :partial => "spree/static_content/static_content_header",
                     :disabled => false)

it should be

>:insert_bottom => "#main-nav-bar ul:first"

or

>:insert_bottom => "#main-nav-bar ul:first-child"

**Comment by JDutil** [comment]
Could you please submit a PR?

**Comment by ristovskiv** [comment]
Sure.
