### ISSUE TITLE
Spree Core 3.1.0.beta Not Found

### ISSUE THREAD

**Issue by emanmarq** [spree-contrib/spree_static_content#189]
When I try to add this gem and bundle I get the following error:
`Could not find gem 'spree_core (~> 3.1.0.beta) ruby', which is required by gem
'spree_static_content (>= 0) ruby', in any of the sources.`

Anyone have any ideas on how to fix this?

**Comment by futhr** [comment]
@emanmarq I assume you are using `master` branches in your project, so just run `bundle update` and you good to go.

**Comment by emanmarq** [comment]
@futhr When I run `bundle update` I get the message:
`Could not find gem 'spree_core (~> 3.1.0.beta) ruby', which is required by gem
'spree_static_content (>= 0) ruby', in any of the sources.`

**Comment by futhr** [comment]
https://github.com/spree/spree/blob/master/SPREE_VERSION
https://github.com/spree-contrib/spree_static_content/blob/master/spree_static_content.gemspec#L25

**Comment by mmintel** [comment]
I am having the same problem, your links didn't help me.. :(

Gemfile:
```
gem 'spree', github: 'spree/spree', branch: 'master'
gem 'spree_gateway', github: 'spree/spree_gateway', branch: '3-0-stable'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '3-0-stable'
gem 'spree_i18n', github: 'spree-contrib/spree_i18n', branch: '3-0-stable'
gem 'spree_static_content', github: 'spree-contrib/spree_static_content', branch: 'master'
```

Terminal
```
$ bundle install
```
```
Bundler could not find compatible versions for gem "spree_core":
  In Gemfile:
    spree_gateway (>= 0) ruby depends on
      spree_core (~> 3.0.0) ruby

    spree_static_content (>= 0) ruby depends on
      spree_core (3.1.0.beta)
```

**Comment by emanmarq** [comment]
I got it to work by just changing the branch on the spree, gateway, auth_devise, and i18n gems to '~> 3.1.0.beta'. Run bundle once you make those changes. That should do it. It seems to working fine for me so far.

Gemfile:

gem 'spree', github: 'spree/spree', branch: '~> 3.1.0.beta'
gem 'spree_gateway', github: 'spree/spree_gateway', branch: '~> 3.1.0.beta'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '~> 3.1.0.beta'
gem 'spree_static_content', github: 'spree-contrib/spree_static_content', branch: 'master'
gem 'spree_i18n', github: 'spree-contrib/spree_i18n', branch: '~> 3.1.0.beta'

**Comment by mmintel** [comment]
@emanmarq that fixed it, thanks!!

**Comment by franciscoGPS** [comment]
Fixed here, too. @emanmarq I was starting feeling frustrated. Thanks a lot. But I have a doubt. How trustworthy is to put a beta version on a production envionment? Talking about Spree. Thanks.
