### ISSUE TITLE
NoMethodError in Spree::Admin::Orders#index for Russian locale

### ISSUE THREAD

**Issue by Kapranov** [spree-contrib/spree_static_content#193]
When we have russian locale We got error
NoMethodError in Spree::Admin::Orders#index
undefined method `%' for :many:Symbol

**Comment by devsli** [comment]
Duplicate of #192

**Comment by futhr** [comment]
@Kapranov dup, issue resolved with cbeaceb1e799568572855777c8b406e900abf571 for `3-0-stable` branch.
