### ISSUE TITLE
Header li items inserted in div#main-nav-bar [3-0-stable]

### ISSUE THREAD

**Issue by devsli** [spree-contrib/spree_static_content#196]
Default menu (branch 3-0-stable):
```html
<div id="main-nav-bar">
  <ul class="nav navbar-nav">
    <li id="home-link">...</li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
    <li id="link-to-cart" data-hook="">...</li>
  </ul>
</div>
```

Static page injected (current behavior):
```html
<div id="main-nav-bar">
  <ul class="nav navbar-nav">
    <li id="home-link">...</li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
    <li id="link-to-cart" data-hook="">...</li>
  </ul>
  <li>... Static page ...</li>
</div>
```
`<li>` was injected into `div#main-nav-bar` due to `:insert_bottom => #main-nav-bar` Deface override (`pages_in_header.rb`)

Expected behavior:
```html
<div id="main-nav-bar">
  <ul class="nav navbar-nav">
    <li id="home-link">...</li>
    <li>... Static page ...</li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
    <li id="link-to-cart" data-hook="">...</li>
  </ul>
</div>
```

Seems fixed in master branch with 42db3f49f9e528ff8f5c7f93101bfe3265e09060

**Comment by sfcgeorge** [comment]
+1 I was about to open the same issue. Seems like an easy backport.

**Comment by cdesch** [comment]
+1 can we please get this merged into the branch @futhr

**Comment by futhr** [comment]
There are failing specs etc that need to be resolved first on `3-0-stable` branch, PR welcome.

**Comment by laurens** [comment]
This has been fixed in 3-0-stable now.
