### ISSUE TITLE
Cannot install gem.

### ISSUE THREAD

**Issue by bishisht** [spree-contrib/spree_static_content#206]
When I try to install the gem following error occurs.
Bundler could not find compatible versions for gem "spree_core":
  In snapshot (Gemfile.lock):
    spree_core (= 3.0.1)

  In Gemfile:
    spree_core (= 3.0.1) ruby

    spree_core (~> 3.0.0) ruby

    spree_core (~> 3.0.0) ruby

    spree_core (~> 3.0) ruby

    spree_static_content (>= 0) ruby depends on
      spree_core (~> 3.1.0.beta) ruby

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
My Gemfile looks like:
source 'https://rubygems.org'
gem 'rails', '4.2.1'
ruby '2.2.2'
gem 'mysql2'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
group :development, :test do
gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
gem 'spree', '3.0.1'
gem 'spree_gateway', github: 'spree/spree_gateway', branch: '3-0-stable'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '3-0-stable'
gem 'rails_12factor', group: :production
gem 'pg', group: :production
gem 'aws-sdk', '< 2.0'
gem 'paperclip'
#gem 'unicorn'
gem 'spree_liqpay', github: 'kukareka/spree_liqpay'
gem 'spree_static_content', github: 'spree-contrib/spree_static_content', branch: 'master'
# gem 'spree_editor'
gem 'puma', group: :production
gem 'spree_paypal_express', github: 'spree-contrib/better_spree_paypal_express', branch: '3-0-stable'
gem 'newrelic_rpm'

**Comment by makaio** [comment]
You probably want to point your branch at stable, as follows:
gem 'spree_static_content', github: 'spree-contrib/spree_static_content', branch: '3-0-stable'

**Comment by ajmyers01** [comment]
I had the same issue, and that was a good fix! Thanks @makaio. Would you like me to create a pull request to update the Readme ?

**Comment by gamut** [comment]
Same here.

You guys really should not put the master branch in the getting started section in the main README file.  Contributors will know they want the master branch, while others will almost always prefer the stable branch.

**Comment by damianlegawiec** [comment]
Done :)

**Comment by gamut** [comment]
Awesome, thank you.
