### ISSUE TITLE
spree_pages_stores table doesnt get populated

### ISSUE THREAD

**Issue by parhs** [spree-contrib/spree_static_content#209]
Hello.
I am using 3.0 stable and this table doesnt get populated resulting in 404 error when try to access pages. My db is postgresql.

**Comment by inyerade** [comment]
same here.
@parhs yo solve the problem?

**Comment by parhs** [comment]
Not sure but I think that you should check the checkbox with your store.

**Comment by inyerade** [comment]
which checkbox?

**Comment by Kevinljh** [comment]
Same problem, anyone help?
