### ISSUE TITLE
Why footer_links was removed in 3-1-stable?

### ISSUE THREAD

**Issue by renatocn** [spree-contrib/spree_static_content#216]
It is very useful and I use it often.

**Comment by damianlegawiec** [comment]
@nishant-cyro @priyank-gupta can you elaborate on this commit (https://github.com/spree-contrib/spree_static_content/commit/55babff8ee534c9af9cec87f7fe47fadd273ad99) ?

**Comment by priyank-gupta** [comment]
@renatocn The commit was merged with PR https://github.com/spree-contrib/spree_static_content/pull/207. Please go through the discussion.

**Comment by renatocn** [comment]
@damianlegawiec @priyank-gupta understood. Thanks.
