### ISSUE TITLE
Is this working in Spree 3.2.0

### ISSUE THREAD

**Issue by jomarbarnobal** [spree-contrib/spree_static_content#229]
just asking if it is work in spree 3.2.0

**Comment by damianlegawiec** [comment]
Yep, master branch works with 3.1, 3.2 and 3.3 (unreleased)

**Comment by jomarbarnobal** [comment]
I made it work in rails 5.0 but i cant get the body content of my page if i check render as partial, and if i unchecked the render as partial i get a template missing error
