### ISSUE TITLE
Mysql2::Error: Table 'development.spree_taxonomy_translations' doesn't exist: SHOW FULL FIELDS FROM `spree_taxonomy_translations`

### ISSUE THREAD

**Issue by paras0092** [spree-contrib/spree_static_content#242]
after run "bundle exec rails g spree_static_content:install" command i have Mysql2::Error: Table 'development.spree_taxonomy_translations' doesn't exist: SHOW FULL FIELDS FROM `spree_taxonomy_translations`

**Comment by jvarleiza** [comment]
Same problem here..

**Comment by imransarfaraz** [comment]
same issue here......

**Comment by krtschmr** [comment]
`/home/tim/.rvm/gems/ruby-2.6.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `_query': Table 'fairshopping_development.spree_taxon_translations' doesn't exist (Mysql2::Error)`


somehow embarassing. it's a year... gg
