### ISSUE TITLE
NoMethodError in Spree::Home#index

### ISSUE THREAD

**Issue by 1fabunicorn** [spree-contrib/spree_static_content#249]
Here is my Gemfile
```
...
gem 'spree', '~> 3.3.0.rc1'
gem 'spree_auth_devise', '~> 3.3'
gem 'spree_gateway', '~> 3.3'

gem 'globalize', github: 'globalize/globalize'
gem 'spree_i18n', github: 'spree-contrib/spree_i18n'
gem 'spree_globalize', github: 'spree-contrib/spree_globalize', branch: 'master'
gem 'spree_static_content', github: 'spree-contrib/spree_static_content'

```

And the error is `undefined method product_for_segment' for #< <Class:0x00000000067273a0>:0x000000000693e940>`

I did everything the README install instructions told me, hopefully this is an easy one!

**Comment by 1fabunicorn** [comment]
After downgrading too rails 5.0, it works. Just a note for the devs.

**Comment by NuclearMachine** [comment]
same here, Taxonomy classes do not work.

**Comment by VygovskySergey** [comment]
@1fabunicorn I have try to reproduce this issue with your config, and everything works fine.
Could you provide exact steps that you have done?

**Comment by nbarthelemy** [comment]
Was this ever resolved? What was the resolution?

**Comment by kbaum** [comment]
Ran into this issue today. I just manually included the missing helper method into application_helper.rb.

```ruby
module ApplicationHelper
  include Spree::TrackersHelper
end
```
