### ISSUE TITLE
methods `find_by` stop working

### ISSUE THREAD

**Issue by NuclearMachine** [spree-contrib/spree_static_content#253]
`find_by_permalink`,`find_by_taxonomy`ETC completely breaks. Please fix.

**Comment by NuclearMachine** [comment]
`2.4.1 :005 > Spree::Taxon.find_by_permalink 'category/flower'
NoMethodError: undefined method `find_by_permalink' for #<Class:0x000000094fcc58>`

`2.4.1 :001 > Spree::Taxonomy.find_by_name("Category")
NoMethodError: undefined method `find_by_name' for #<Class:0x0000000c57f268>`

**Comment by VygovskySergey** [comment]
@NuclearMachine Is it just problem with `spree_static_content`, or you have the same problem for regular `spree` application?

**Comment by NuclearMachine** [comment]
@VygovskySergey the said methods worked completely fine until i bundled the `spree_static_content` gem and its prerequisites with my app

**Comment by VygovskySergey** [comment]
@NuclearMachine Thanks, I will try to configure what is going wrong

**Comment by VygovskySergey** [comment]
@NuclearMachine I think i got what the problem with this, after you added `spree_globalize`,`taxon`s fields like `name`, `description`, `permalink` is going to another model, so basically you dont have these fields in your model.
