### ISSUE TITLE
Problems with Spree 4.0

### ISSUE THREAD

**Issue by Gemsys** [spree-contrib/spree_static_content#270]
Hi, 

I have tried to install Spree Static Content on a fresh installation of Spree 4.0
After running "bundle exec rails g spree_static_content:install" I get the following error:
/home/tore/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/
load_path_cache/core_ext/kernel_require.rb:22:in `require': cannot load such file -- coffee_script (LoadError)
....

Please suggest or guide

Thanks!

**Comment by damianlegawiec** [comment]
Fixed, please do `bundle update spree_static_content`
