### ISSUE TITLE
Caching and expiring pages

### ISSUE THREAD

**Issue by greinacker** [spree-contrib/spree_static_content#55]
Since I just fixed the remaining cache-key-name problem, and I'm working with this on a new site, I'm discovering a process issue.  Suppose the following:
1. I go in and add a few static pages A and B, and add them to the header.
2. People visit the site, pages A and B get cached as expected.
3. I then add a new static page C, and also add it to the header.

Now when people request page C, everything looks great and the header has A, B, and C.

But when people request pages A or B, there are still cached versions of those pages that don't have page C in the header, since the header is part of what's cached.

I can think of a few ways to fix this:
1. We could use fragment caching and only cache the page content, excluding all of the layout.
2. We could expire ALL of the cached pages whenever any page is edited (we currently just expire the page that was edited)
3. We could have a button on the Admin/Pages tab to expire all pages.

Any thoughts?

**Comment by baraka2000** [comment]
I know this is really old, but I am still using 1.1 and having the same problem, even with cache disabled. Essentially I change my content, but my browser is not seeing this as a new file to load, so I just get the cached content. Any ideas?
